name=WOCO
version=0.1.0
author=Tobias Knauss <tobias.knauss@web.de>
maintainer=Tobias Knauss <tobias.knauss@web.de>
sentence=Worker Command Protocol
paragraph=Collection of commands and parameters for worker devices (usually communicated via UCOP).
category=Communication
url=https://github.com/TobiasKnauss/ArduinoLib_WOCO
architectures=*
